
// This file has been generated by the GUI designer. Do not modify.
namespace UVAArena
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action Action;
		
		private global::Gtk.Action UVAArenaAction;
		
		private global::Gtk.Action closeAction;
		
		private global::Gtk.Action ProblemsAction;
		
		private global::Gtk.Action CodesAction;
		
		private global::Gtk.Action StatusAction;
		
		private global::Gtk.Action ProfilesAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action helpAction;
		
		private global::Gtk.Action dialogQuestionAction;
		
		private global::Gtk.Action FacebookPageAction;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.MenuBar menubar2;
		
		private global::Gtk.Notebook notebook6;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Statusbar statusbar6;
		
		private global::Gtk.ProgressBar progressbar2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UVAArena.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.UVAArenaAction = new global::Gtk.Action ("UVAArenaAction", global::Mono.Unix.Catalog.GetString ("UVA Arena"), null, null);
			this.UVAArenaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("UVA Arena");
			w1.Add (this.UVAArenaAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.closeAction, null);
			this.ProblemsAction = new global::Gtk.Action ("ProblemsAction", global::Mono.Unix.Catalog.GetString ("Problems"), null, null);
			this.ProblemsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Problems");
			w1.Add (this.ProblemsAction, null);
			this.CodesAction = new global::Gtk.Action ("CodesAction", global::Mono.Unix.Catalog.GetString ("Codes"), null, null);
			this.CodesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Codes");
			w1.Add (this.CodesAction, null);
			this.StatusAction = new global::Gtk.Action ("StatusAction", global::Mono.Unix.Catalog.GetString ("Status"), null, null);
			this.StatusAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Status");
			w1.Add (this.StatusAction, null);
			this.ProfilesAction = new global::Gtk.Action ("ProfilesAction", global::Mono.Unix.Catalog.GetString ("Profiles"), null, null);
			this.ProfilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Profiles");
			w1.Add (this.ProfilesAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Online Help"), null, "gtk-help");
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Online Help");
			w1.Add (this.helpAction, null);
			this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-dialog-question");
			this.dialogQuestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.dialogQuestionAction, null);
			this.FacebookPageAction = new global::Gtk.Action ("FacebookPageAction", global::Mono.Unix.Catalog.GetString ("Facebook Page"), null, null);
			this.FacebookPageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Facebook Page");
			w1.Add (this.FacebookPageAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "UVAArena.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("UVA Arena");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child UVAArena.MainWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar2'><menu name='UVAArenaAction' action='UVAArenaAction'><menuitem name='closeAction' action='closeAction'/></menu><menu name='ProblemsAction' action='ProblemsAction'/><menu name='CodesAction' action='CodesAction'/><menu name='StatusAction' action='StatusAction'/><menu name='ProfilesAction' action='ProfilesAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><menuitem name='dialogQuestionAction' action='dialogQuestionAction'/><separator/><menuitem name='FacebookPageAction' action='FacebookPageAction'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox4.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notebook6 = new global::Gtk.Notebook ();
			this.notebook6.CanFocus = true;
			this.notebook6.Name = "notebook6";
			this.notebook6.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this.notebook6.Add (w3);
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xpad = 30;
			this.label10.Ypad = 6;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("PROBLEMS");
			this.notebook6.SetTabLabel (w3, this.label10);
			this.label10.ShowAll ();
			// Notebook tab
			global::Gtk.Label w4 = new global::Gtk.Label ();
			w4.Visible = true;
			this.notebook6.Add (w4);
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xpad = 30;
			this.label11.Ypad = 6;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("CODES");
			this.notebook6.SetTabLabel (w4, this.label11);
			this.label11.ShowAll ();
			// Notebook tab
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.Visible = true;
			this.notebook6.Add (w5);
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xpad = 30;
			this.label12.Ypad = 6;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("STATUS");
			this.notebook6.SetTabLabel (w5, this.label12);
			this.label12.ShowAll ();
			// Notebook tab
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.Visible = true;
			this.notebook6.Add (w6);
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xpad = 30;
			this.label13.Ypad = 6;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("PROFILES");
			this.notebook6.SetTabLabel (w6, this.label13);
			this.label13.ShowAll ();
			this.vbox4.Add (this.notebook6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.notebook6]));
			w7.Position = 1;
			w7.Padding = ((uint)(2));
			// Container child vbox4.Gtk.Box+BoxChild
			this.statusbar6 = new global::Gtk.Statusbar ();
			this.statusbar6.Name = "statusbar6";
			this.statusbar6.Spacing = 4;
			// Container child statusbar6.Gtk.Box+BoxChild
			this.progressbar2 = new global::Gtk.ProgressBar ();
			this.progressbar2.Name = "progressbar2";
			this.statusbar6.Add (this.progressbar2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar6 [this.progressbar2]));
			w8.Position = 1;
			w8.Expand = false;
			this.vbox4.Add (this.statusbar6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.statusbar6]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Padding = ((uint)(2));
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 733;
			this.DefaultHeight = 433;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		}
	}
}
